### ISSUE TITLE
7th Plan by Jiyeon

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#45]
# Plan 

## 가장 먼저 해야할 일
- [x] DB - Web Server 통신하기 수정 (매뉴얼대로 따라하기)
- [x] Wiki에 정리하기([Express예제](https://github.com/JEoN-Ha/Senior-Project/wiki/Express%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-DB%EC%99%80-Sever%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0(%EA%B0%80%EC%A0%9C,%EC%9E%91%EC%84%B1%EC%A4%91)) 삭제 or 수정하기)

## todo
- [ ] DB Design
- [ ] 앱에 사용될 DB 만들기

# Time
- [x] 12월 29일 2시간
- [x] 12월 30일 2시간
- [x] 12월 31일 2시간
- [x] 1월2일 2시간
- [x] 1월3일 2시간

## Reference
[기존 Azure App Service를 Azure Database for MySQL 서버에 연결](https://docs.microsoft.com/ko-kr/azure/mysql/howto-connect-webapp)

**Comment by kiJiyeon** [comment]
12/29 작업시작

**Comment by kiJiyeon** [comment]
중단

**Comment by kiJiyeon** [comment]
다시시작

**Comment by kiJiyeon** [comment]
종료

으악

**Comment by kiJiyeon** [comment]
12/30 작업시작

**Comment by kiJiyeon** [comment]
중단

**Comment by kiJiyeon** [comment]
다시시작

**Comment by kiJiyeon** [comment]
작업종료

**Comment by kiJiyeon** [comment]
작업시작

**Comment by kiJiyeon** [comment]
작업종료

**Comment by kiJiyeon** [comment]
1/2 작업시작

**Comment by kiJiyeon** [comment]
작업종료

**Comment by kiJiyeon** [comment]
1/3 작업시작
