### ISSUE TITLE
구체적인 Server TODO

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#49]
# Server TODO
- [x] DB Design(구성도) 하기
- [x] DB Design에 따른 Table 정의 및 관계 짓기 -> 간단히 말해 실제 DB 구축
- Express를 이용해 DB(Server)에서 Web(Server)와 통신
  - [ ] DB(Server)에서 Web(Server)에 Data 띄우기
  - [ ] Web(Server)에서 DB(Server)로 데이터를 넣을 때 Table에 row(행)가 추가되도록 설정

내가 생각하기에는 윗 내용 Server가 해야할 일인데(더 있다면 추가 바람) 담당자를 명확히 정하고 싶음. 이에 관해서 의견 바람.

**Comment by kiJiyeon** [comment]
음 DB Design은 DB Server랑 WEB Server 통신 성공한 다음에 어떻게 만들지 생각해보려고 했었는데,
일단 **내가 담당하는게 맞는것 같음!!  

그리고 오빠가 
 내가 디자인 해서 보여주면 _이렇게 고쳤으면 좋겠다 or 이런것도 있더라_ 뭐 이런식으로 **감독하는 역할**을 해주면 되지않을까?!

어떰??

**Comment by fora22** [comment]
> 음 DB Design은 DB Server랑 WEB Server 통신 성공한 다음에 어떻게 만들지 생각해보려고 했었는데,
> 일단 **내가 담당하는게 맞는것 같음**!!
> 
> 그리고 오빠가
> 내가 디자인 해서 보여주면 _이렇게 고쳤으면 좋겠다 or 이런것도 있더라_ 뭐 이런식으로 **감독하는 역할**을 해주면 되지않을까?!
> 
> 어떰??

음..**감독하는 역할**(어감이 그러니 **매니징을 한다**고 하자)은 좋은데 그러면 지금 당장 내가 할 일이 없어서(있어봤자 Redux 강의 듣기?) 나에게 시켰으면 하는 일이 있니??

**Comment by kiJiyeon** [comment]
혹시 그럼 [기존 Azure App Service를 Azure Database for MySQL 서버에 연결](https://docs.microsoft.com/ko-kr/azure/mysql/howto-connect-webapp) 이거 참고해서 **DB랑 Web서버랑 연결**하는거 오빠도 해보면 안될까?? 
자꾸 SSL 오류뜨는데 해결을 못하고있어 ㅜㅜ 

 -> 둘중에 한명이 성공한 방법으로 진행하는 작전!!

**Comment by fora22** [comment]
> 혹시 그럼 [기존 Azure App Service를 Azure Database for MySQL 서버에 연결](https://docs.microsoft.com/ko-kr/azure/mysql/howto-connect-webapp) 이거 참고해서 **DB랑 Web서버랑 연결**하는거 오빠도 해보면 안될까??
> 자꾸 SSL 오류뜨는데 해결을 못하고있어 ㅜㅜ
> 
> -> 둘중에 한명이 성공한 방법으로 진행하는 작전!!

오키! 확인!

진행하고 진행결과 공유하겠음!
