### ISSUE TITLE
8th Plan by Jiyeon

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#57]
# To-do
## 가장 먼저 할 일

- [x] Azure 체험 계정 구하기
- [x] DB 서버 Web 서버 연결하기(Express & rest api 활용)

## What's next
- [x] DB Design(#54 참고) 
- [ ] Wiki에 정리하기

# Time
- [x] 1/5 2시간
- [x] 1/6 2시간
- [x] 1/7 2시간
- [ ] 1/8 2시간
- [x] 1/9 2시간
- [x] 1/10 2시간

### Linked Issue

#59
 
## Reference 
[[React 개발 ] 01. React에 Express 연동하기](https://nextus.tistory.com/21?category=802228)
[Rest](https://medium.com/@hckcksrl/rest%EB%9E%80-c602c3324196)
[React-mysql연결](https://coding-hyeok.tistory.com/23)

**Comment by kiJiyeon** [comment]
1/5 작업시작

**Comment by kiJiyeon** [comment]
1/5 작업시작

**Comment by kiJiyeon** [comment]
## 참고자료 모음

1. What is Rest api?
- [REST API 제대로 알고 사용하기](https://meetup.toast.com/posts/92)
2.

**Comment by kiJiyeon** [comment]
작업종료

**Comment by kiJiyeon** [comment]
1/5 2차 시작

**Comment by kiJiyeon** [comment]
작업종료

**Comment by kiJiyeon** [comment]
1/6 작업시작

**Comment by kiJiyeon** [comment]
일단 작업종료

**Comment by kiJiyeon** [comment]
1/7 작업 시작

**Comment by kiJiyeon** [comment]
일단 작업 종료 

지금까지 한거에 + #61 의 예제 따라하면서 보완하기

**Comment by kiJiyeon** [comment]
진짜 작업종료

**Comment by kiJiyeon** [comment]
1/8 작업시작

**Comment by kiJiyeon** [comment]
작업 종료

`'ECONNRESET'` 에러 해결하기

**Comment by kiJiyeon** [comment]
1/9 작업시작

**Comment by kiJiyeon** [comment]
`Uncaught (in promise) TypeError: Failed to fetch` Error해결하기

- [promise 함수](https://velog.io/@dooreplay/%EC%9C%84%EC%BD%94%EB%93%9C-5-6%EC%9D%BC%EC%B0%A8-TIL-js-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%ED%95%A8%EC%88%98%EC%99%80-json-%EB%8D%B0%EC%9D%B4%ED%84%B0-7gjywv7yz4)

**Comment by kiJiyeon** [comment]
작업종료

내일은 #59의 `DB 테이블 구성도를 보고 DB구현하기(#54 )`부터 시작

**Comment by kiJiyeon** [comment]
1/10 작업시작

**Comment by kiJiyeon** [comment]
https://www.youtube.com/playlist?list=PLuHgQVnccGMDF6rHsY9qMuJMd295Yk4sa

**Comment by kiJiyeon** [comment]
작업종료 

 버튼 누르면 거기에 맞는 데이터 출력 되게 하고싶었는데 못함 ㅜ 내일의 지연 화이팅

**Comment by kiJiyeon** [comment]
작업시작

**Comment by kiJiyeon** [comment]
case문으로 key 값마다 fetch를 다르게

**Comment by kiJiyeon** [comment]
작업종료
