### ISSUE TITLE
Server TODO 2

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#59]
# DB(Server)와 Web(Server) 통신
## 활용도구(예상)
- REST
- Express
- `fetch()` 함수

## TEST
- [x] DB(Server)에서 Web(Server)에 Data 띄우기
- [ ] Web(Server)에서 DB(Server)로 데이터를 넣을 때 Table에 row(행)가 추가되도록 설정

## 실제 구현
- [x] #54 의 DB Table 구성도를 보고 DB 구현
- [ ] 실제 우리의 홈페이지(Jeonha)에서 DB에서 통신을 통해 홈페이지에 표시되도록 하기(예: `store`의 `state`로 넣어두기, 주문 혹은 장바구니 버튼을 누르면 DB Update 등)

# 기본적인 Reference
- [Express 공식 홈페이지](https://expressjs.com/ko/)
- [REST란](https://medium.com/@hckcksrl/rest%EB%9E%80-c602c3324196)
- [[ React 개발 ] 01. React에 Express 연동하기](https://nextus.tistory.com/21?category=802228)

**Comment by fora22** [comment]
`unexpected token o in json at position 0` 이거 원인 찾았음!! @kiJiyeon 

`fetch()`에서 
```js
fetch('http://localhost:3000/')
    .then(response => {
      console.log(response);
    });
```
을 실행해보면 response 자체가 json 형태임! 그래서 json 두번 parse했다고 저 에러가 뜬 것으로 보임
```js
// 원래 코드
fetch('https://koreanjson.com/posts/1')
  .then(response => response.json()) // 이 부분
  .then(json => console.log(json))
```

실제로 `response`값을 봤더니 아래 사진처럼 뜸. 하지만 데이터는 어떻게 가져와야 하는지 잘 모르겠음(현재상황 공유)
![image](https://user-images.githubusercontent.com/48875566/104013759-4320ea00-51f5-11eb-8a71-fc0cb51f045f.png)

**Comment by fora22** [comment]
근데 가능성의 하나로 서버에서 거절당했을 가능성도 있음

**Comment by kiJiyeon** [comment]
헉 이런,,,, 지금부터 작업하면서 참고할게!! 감솨

**Comment by fora22** [comment]
# 현재상황
![image](https://user-images.githubusercontent.com/48875566/104092861-1094f100-52ca-11eb-9b0d-dd44e0a5e34f.png)

`fetch()` 함수로 데이터 가져오고 Object 형태로 parse 하는 것은 성공

이제 남은 것은 data를 db쪽에 update 및 delete 해서 반영이 되는지 알아봐야 함.
 
그 다음 WEB에 적용.

**Comment by kiJiyeon** [comment]
오빠 우리 상단 메뉴바 클릭하면 알맞는 데이터 불러오는거 어떤 방식으로 할까????

1. 누를 때마다 다른 페이지 뜨게한다. `Ex. http://localhost:3000/menu`
2. 화면 안바뀌고 그 안에서 component만 변한다.
