### ISSUE TITLE
9th Plan by fora22

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#71]
# First To Do
- [x] React-Router 문제에 대한 문제 설명 추가 #64 
- [x] '긴급' -> '중요' Labeling 적용에 관해 README 수정하고 다시 Review Request #65 
- [x] 공유 Reference Issue 발행 #72 

# Server To Do
- [x] `fetch()`를 통해 DB Insert, Update, Delete 테스트하기
- [ ] Swagger 를 활용한 Api Design
 
# 이미지 처리 To Do
## 자료조사하기
- [x] 공유 Reference Issue 에 이미지 처리 관련 Reference 올리기
- [ ] Azuire Api 사용해보기

# TIME
- [x] 평일 5시간
- [x] 주말 2시간

**Comment by fora22** [comment]
작업시작
