### ISSUE TITLE
Server ToDo 3

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#74]
## 담당자 지정
 지연, 대원의 `8th Plan` (#69 , #71 )이 전반적으로 거의 똑같음 + **똑같은 일을 굳이 두명이 해야할 필요가 없기 때문**에, 담당자를 지정해서 역할을 분배하는 것이 좋다고 판단!!

# 역할분배 내용
 ## 지연
- [x] `Swagger` 이용하여 api  문서 만들기(DB Design)
- [x] Wiki정리하기 (서버 구축, DB구축, Swagger로 api문서화하기)
## 대원
- [x] `fetch()`를 통해 DB Insert, Update, Delete 테스트하기
- [ ] router code 쓰기 
- [x] `Azure` 예제 찾기 및 실습하기

**Comment by fora22** [comment]
본인 두둥등장!

> * [ ]  `Postman` 사용하여 client에 데이터 보내기

일단 이거는 필요성이 있는지 알고 싶음!

**Comment by kiJiyeon** [comment]
음 일단 필요없을까?? 사실 저번 멘토님이랑 오프라인 미팅때도 그렇고 8th 온라인 미팅때도 언급하셔서 "오옹,, 한번 해봐야겠다"하고 넣었어

**Comment by kiJiyeon** [comment]
오이오이 나 기동민 생파좀 하고올게

**Comment by fora22** [comment]
> 오이오이 나 기동민 생파좀 하고올게

그러면 그냥 생파하고 내일 얘기 다시 나눠보자

**Comment by kiJiyeon** [comment]
그리고 
>  `Cloud 에서 Api를 통해 이미지 분류를 해주는 서비스 찾기`이건 #73에 언급된 `Azure 이미지 처리`냐 `GCP`를 사용하느냐 이건가?

**Comment by kiJiyeon** [comment]
> > 오이오이 나 기동민 생파좀 하고올게
> 
> 그러면 그냥 생파하고 내일 얘기 다시 나눠보자 ㅋㅋㅋㅋㅋㅋㅋㅋ
> 
> 동민이한테 생일 축하한다고 전해줘!

고마워!!!!!!!!!!!!!!!!!!!!

**Comment by kiJiyeon** [comment]
오빠!!!! 나왔어!!!!!!!!!!

**Comment by kiJiyeon** [comment]
아 내일 얘기 하자고 했구나 치킨먹을 생각ㅇ에 설레서 좀따라고 봤음 ㅋㅋㅋㅋㅋ

**Comment by dkfma4915** [comment]
> 오이오이 나 기동민 생파좀 하고올게

동민이 생일추카해~~~~~!

**Comment by kiJiyeon** [comment]
https://github.com/JEoN-Ha/Senior-Project/blob/7eccff4db11f10510d8368b9dad007ecb1fd0ab9/fora22/DB/initDB.sql#L1-L74

**Comment by kiJiyeon** [comment]
![image](https://user-images.githubusercontent.com/48858836/104716807-bda8b700-576b-11eb-94cd-25ea7ab3ae2b.png)

![image](https://user-images.githubusercontent.com/48858836/104716822-c4372e80-576b-11eb-98d5-a18480983304.png)


일단 이정도로 테스트 해봤는데,  대원오빠 router code정리 다 됐엉?!?!

**Comment by fora22** [comment]
> 일단 이정도로 테스트 해봤는데,  대원오빠 router code정리 다 됐엉?!?!

router code는 swagger 완성 안되면 못만들엉!

그리구 너가 올린거 혹시 fetch 한거니?? 그거 내 담당인뎅

**Comment by kiJiyeon** [comment]
> > 일단 이정도로 테스트 해봤는데,  대원오빠 router code정리 다 됐엉?!?!
> 
> router code는 swagger 완성 안되면 못만들엉!
> 
> 그리구 너가 올린거 혹시 fetch 한거니?? 그거 내 담당인뎅

웅??? 나 fetch 안건드리고,테스트하려고  router.get안쪽에  쿼리문 바꾼것밖에 없는데! 
그리고 router완성돼야 swagger로 문서화할 수 있는거 아냐?? 

``` 
openapi: 3.0.0
info: 
  version: '1.0.0'
  title: Untact DriveThru API
  description: this is for Senior Project of Jeonha
servers:
  - description: Jeonha API
    url: http://localhost:4000/
paths:
  /getData:
    get:
      summary: GetData API
      parameters: 
        - in: query
          name: USerWebId
          description: user id 
          required: true
          schema:
              type: object
        - in: query
          name: CarWebId
          description: to figure out whose car is this
          required: true
          schema:
              type: object
resposes: 
  '200':
    description: query successful !
    schema: 
      type: object

```
위에`paths` 아랫 부분에 parameter 속성 쓸 때,  어떤 변수가 어떤 역할인지, 어떤 형인지 알아야 할 수 있는거라고 생각했는뎁

**Comment by fora22** [comment]
Swagger로 어떤 데이터가 오가고 어떤 타입인지 정해야 코드로 구현하는게 맞을 거 같은데?

구성도 그린 다음에 DB 구현하듯이!

타입은 내가 말한 DB파일에 타입  다 명시돼있음(initDB.sql 파일)

**Comment by kiJiyeon** [comment]
> Swagger로 어떤 데이터가 오가고 어떤 타입인지 정해야 코드로 구현하는게 맞을 거 같은데?
> 
> 구성도 그린 다음에 DB 구현하듯이!
> 
> 타입은 내가 말한 DB파일에 타입 다 명시돼있음(initDB.sql 파일)

근데 윗 댓에 `paths` 밑에보면, url 뒷부분(<-이거 용어 뭔지 잘 모르겠다,,,)이 `/getData` 일 때 쓰이는 parameter들인데,  다른 `/something`에서는 어떤 것들이 쓰이는지 정해지지 않았으니까 못쓴다고 생각했는데! 

아니면 아름이가 정리해서 주는걸 보고 작성을 해야하는건가?

**Comment by fora22** [comment]
그걸 정하는게 swagger 파트이고 아름이가 주는거로 하는 것도 맞는데 직접 디자인 해도 되긴 해

**Comment by kiJiyeon** [comment]
음 그럼 오케이! 확인~

**Comment by kiJiyeon** [comment]
오빠 일단 api 문서화 작성은 다했는데 확인 해줘!!!  
`jiyeonki/feature/swagger`브랜치에 `jeonha-redux\public` 폴더에 `swagger.yaml`파일임!! 

수정해야할 것들 말해줭

**Comment by kiJiyeon** [comment]
오빠 나 `swagger.yaml`파일 다 작성했는데, 확인부탁~! 수정해야할것들 있으면 말해줘

`jiyeonki/Feature/swagger`브랜치에 `jiyeon\jeonha-redux\public`위치에 `swagger.yaml`임!

**Comment by fora22** [comment]
> 오빠 나 `swagger.yaml`파일 다 작성했는데, 확인부탁~! 수정해야할것들 있으면 말해줘
> 
> `jiyeonki/Feature/swagger`브랜치에 `jiyeon\jeonha-redux\public`위치에 `swagger.yaml`임!

이거는 PR로 올려주면 좋을  것 같아!!
