### ISSUE TITLE
1.5st review meeting

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#8]
# 2020년 12월 19일 (금) Meeting 
시간 : 오전 10시 30분 ~ 오후 4시

장소 : 404호

# TODO List
- [x] 박상준 교수님 논문 미팅
- [x] 그리고 또 뭘하지?
  
  -> 그래서 준비했다.
  1. VanillaJS(JavaScript) 실습(문제(?) 풀기)
     - 각자 웹페이지 하나 골라서 클론 코딩하기
     - VanillaJs는 순수한 JavaScript를 말함.
  2. React, Vue 실습(Hello world 예제 까지)
  3. 각자 논문 진행

위 3개 중 골라서 진행하거나, 다른 의견 있으면 코멘트 주기 바람~

**Comment by dkfma4915** [comment]
그 교수님이 고치라고 말해주신 부분 (iteration별 BER구하기)은 셋 다 해야할 부분이니까 같이 해보는건 어떠신가요???

**Comment by fora22** [comment]
> 그 교수님이 고치라고 말해주신 부분 (iteration별 BER구하기)은 셋 다 해야할 부분이니까 같이 해보는건 어떠신가요???

좋은 생각이네요. 그래도 조금 시간이 남을 것 같은데 추가 의견 있으신가요~ @dkfma4915

**Comment by kiJiyeon** [comment]
저는 셋중에 고른다면 **ii.React, Vue 실습**을 하는게 좋을것같습니다~
(+ React랑 Vue중에 뭘 쓸지 정하기..?)

**Comment by dkfma4915** [comment]
> > 그 교수님이 고치라고 말해주신 부분 (iteration별 BER구하기)은 셋 다 해야할 부분이니까 같이 해보는건 어떠신가요???
> 
> 좋은 생각이네요. 그래도 조금 시간이 남을 것 같은데 추가 의견 있으신가요~ @dkfma4915

음 지연이와 같은 의견~~~!
+ 취준 관련 이야기(?) : 뉴스기사, 중국어, 스터디, 공정실습
(요새 고민하고 있거나 알려주고 싶은 꿀팁 전달!!)

**Comment by fora22** [comment]
정리하자면~
# 2020년 12월 19일 (금) Meeting 
시간 : 오전 10시 30분 ~ 오후 4시

장소 : 404호

# TODO List
- [ ] 박상준 교수님 논문 미팅
- [ ] iteration 별 BER 구하기 구현
- [ ] React, Vue 실습(Hello world 예제 까지)
- [ ] 취준 관련 이야기(?) : 요새 고민하고 있거나 알려주고 싶은 꿀팁 전달!!
  - 뉴스기사
  - 중국어
  - 스터디
  - 공정실습

추가 의견 또 있으면 말해주세요~~
