### ISSUE TITLE
11th Plan by Jiyeon

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#89]
# To-Do (이번주 내로 꼭 해결하기 ㅜㅜ)
- [ ] cors 에러 해결하기
- [ ] api 잘 작동하는지 확인(어떤 오류인지 확인하고 고치기)
- [x] #83 정리해서 comment 달기

# Time
- [x] 2/18 2시간
- [x] 2/19 2시간

**Comment by kiJiyeon** [comment]
작업 종료
Unhandled Rejection (SyntaxError): Unexpected end of input

**Comment by kiJiyeon** [comment]
작업종료,,,

**Comment by kiJiyeon** [comment]
이제,,,,이것만 해치우면,,,,,,
![image](https://user-images.githubusercontent.com/48858836/109187315-20fb1f80-77d5-11eb-93a2-431506b218eb.png)

**Comment by kiJiyeon** [comment]
이자식만 없어지면,,,,,
![image](https://user-images.githubusercontent.com/48858836/109330228-ce863580-789e-11eb-9b97-fa7b848566ce.png)
